 youtube-dl --ignore-config --get-id http://pscp.tv/AngelMarie/ >   .sh
 youtube-dl --ignore-config --get-id http://pscp.tv/AverageSwingers/ >   .sh
 youtube-dl --ignore-config --get-id http://pscp.tv/FetishDollEmily/ >   .sh
 youtube-dl --ignore-config --get-id http://pscp.tv/FunLG/ >   .sh
 youtube-dl --ignore-config --get-id http://pscp.tv/KaashButter/ >   .sh
 youtube-dl --ignore-config --get-id http://pscp.tv/KinoYoga/ >   .sh
 youtube-dl --ignore-config --get-id http://pscp.tv/LanieLynnXXX >   .sh
 youtube-dl --ignore-config --get-id http://pscp.tv/StephyScopes/ >   .sh
 youtube-dl --ignore-config --get-id http://pscp.tv/SwingerMexico_/ >   .sh
 youtube-dl --ignore-config --get-id http://pscp.tv/YoungLiving87/ >   .sh
 youtube-dl --ignore-config --get-id http://pscp.tv/YourOasisRadio/ >   .sh
 youtube-dl --ignore-config --get-id http://pscp.tv/arabellamascari >   .sh
 youtube-dl --ignore-config --get-id http://pscp.tv/ariesqueen_/ >   .sh
 youtube-dl --ignore-config --get-id http://pscp.tv/dankkcoffee/ >   .sh
 youtube-dl --ignore-config --get-id http://pscp.tv/harper_cox_ >   .sh
 youtube-dl --ignore-config --get-id http://pscp.tv/kaylorsaurus >   .sh
 youtube-dl --ignore-config --get-id http://pscp.tv/konmann702/ >   .sh
 youtube-dl --ignore-config --get-id http://pscp.tv/ready2jam1/ >   .sh
 youtube-dl --ignore-config --get-id http://pscp.tv/sammisacavage/ >   .sh
 youtube-dl --ignore-config --get-id http://pscp.tv/sheslulu/ >   .sh
 youtube-dl --ignore-config --get-id http://pscp.tv/veradevera/ >   .sh
 youtube-dl --ignore-config --get-id http://pscp.tv/thereallisaann/ >   .sh
 youtube-dl --ignore-config --get-id http://pscp.tv/imutimes/ >   .sh
 youtube-dl --ignore-config --get-id http://pscp.tv/allycat77/ >   .sh
 youtube-dl --ignore-config --get-id http://pscp.tv/anireal/ >   .sh
 youtube-dl --ignore-config --get-id http://pscp.tv/TheDabSpot/ >   .sh
