
ruby fetch.rb -n http://ajdudebro.deviantart.com/gallery/
ruby fetch.rb -n http://alexandrab24.deviantart.com/gallery/
ruby fetch.rb -n http://arrrgyle.deviantart.com/gallery/
ruby fetch.rb -n http://cyncaelyx.deviantart.com/gallery/
ruby fetch.rb -n http://digital-snapshots.deviantart.com/gallery/
ruby fetch.rb -n http://hussard-yr.deviantart.com/gallery/
ruby fetch.rb -n http://jabbym.deviantart.com/gallery/
ruby fetch.rb -n http://jessicaelwood.deviantart.com/gallery/
ruby fetch.rb -n http://jynos.deviantart.com/gallery/
ruby fetch.rb -n http://kuvshinov-ilya.deviantart.com/gallery/
ruby fetch.rb -n http://marlomarquise.deviantart.com/gallery/
ruby fetch.rb -n http://otfs.deviantart.com/gallery/
ruby fetch.rb -n http://rizzyda.deviantart.com/gallery/
ruby fetch.rb -n http://salmoneatjo0.deviantart.com/gallery/
ruby fetch.rb -n http://s-c.deviantart.com/gallery/
ruby fetch.rb -n http://sourcefilmmaker.deviantart.com/gallery/
ruby fetch.rb -n http://tainted-kayla.deviantart.com/gallery/
ruby fetch.rb -n http://thesourkraut.deviantart.com/
ruby fetch.rb -n http://urbanator.deviantart.com/gallery/
ruby fetch.rb -n http://xenolsvectors.deviantart.com/gallery/
ruby fetch.rb -n http://yanhost.deviantart.com/gallery/
ruby fetch.rb -n https://hakusfm.deviantart.com/
