ruby fetch.rb -n https://ajdudebro.deviantart.com/gallery/
ruby fetch.rb -n https://alexandrab24.deviantart.com/gallery/
ruby fetch.rb -n https://arrrgyle.deviantart.com/gallery/
ruby fetch.rb -n https://cyncaelyx.deviantart.com/gallery/
ruby fetch.rb -n https://digital-snapshots.deviantart.com/gallery/
ruby fetch.rb -n https://hussard-yr.deviantart.com/gallery/
ruby fetch.rb -n https://jabbym.deviantart.com/gallery/
ruby fetch.rb -n https://jessicaelwood.deviantart.com/gallery/
ruby fetch.rb -n https://jynos.deviantart.com/gallery/
ruby fetch.rb -n https://kuvshinov-ilya.deviantart.com/gallery/
ruby fetch.rb -n https://marlomarquise.deviantart.com/gallery/
ruby fetch.rb -n https://otfs.deviantart.com/gallery/
ruby fetch.rb -n https://rizzyda.deviantart.com/gallery/
ruby fetch.rb -n https://salmoneatjo0.deviantart.com/gallery/
ruby fetch.rb -n https://s-c.deviantart.com/gallery/
ruby fetch.rb -n https://sourcefilmmaker.deviantart.com/gallery/
ruby fetch.rb -n https://tainted-kayla.deviantart.com/gallery/
ruby fetch.rb -n https://thesourkraut.deviantart.com/
ruby fetch.rb -n https://urbanator.deviantart.com/gallery/
ruby fetch.rb -n https://xenolsvectors.deviantart.com/gallery/
ruby fetch.rb -n https://yanhost.deviantart.com/gallery/
ruby fetch.rb -n https://hakusfm.deviantart.com/
ruby fetch.rb -n https://splashbrush.deviantart.com/gallery/
