youtube-dl --get-id --ignore-error  http://youtube.com/channel/UC0SInoBjrT0rjYYatww7EiA > doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/channel/UC0n0NnchNjAT6K8OpEi5LdQ >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/channel/UC11i8bbVwU9X__YRImykflw >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/channel/UC3Kgs-FyO-mmrXjzipxyvww >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/channel/UC6Y0OnPOJhn1ZpdWOLanE5Q >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/channel/UC7Xvb6vnx4ADvyXFisUhFyw  >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/channel/UC9xHsDvaDKCLWo4SerOtYdA >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/channel/UCAnax9HdSQy1GQsGyXttKDQ >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/channel/UCE-RCPNfQZU1_fioN7G6B6w >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/channel/UCF88rJsqCxmuc521py9MI8w >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/channel/UCFhhjsNJiLrRS1TcFnwOYGg >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/channel/UCFq0ipiIzhlHrp0lur4496g >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/channel/UCFzv5JEx2WBIYf8JhVMqqaw >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/channel/UCHg23qhb1SQl5b6kmZpELrQ >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/channel/UCIlWky-zNDoNU4eHTvfu1BQ >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/channel/UCIr4wYu1mzuowfwfE3RZkiw >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/channel/UCIzAn--9GtaMcek_RmkW3YQ >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/channel/UCK_3N4ldsPufN-0PtoHXH1A >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/channel/UCLGtqbILKgn53RjpgctUgWw >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/channel/UCLJTepxffpGcFtL-UHxrWIw >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/channel/UCMqxeEfcrCh38nV3UsL1AcQ >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/channel/UCQmfoAzx0PfoomW6hgCoqQA >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/channel/UCQsw5mAeC956hSnrVyPA-Rg >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/channel/UCR0Wq_aYgTEg8Z3rP9kj8Hw >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/channel/UCTMq7pbt1QnmVrqwk9dVE2A >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/channel/UCTW2DcB38U_1rplujOY-SAg >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/channel/UCUOb4lgSDckZoBzgcvylaLQ >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/channel/UCUvdK__z3mLqmRCOLIPSVbw >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/channel/UCVx991b_NjWJU94TGwuc2uw >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/channel/UCXtgoWAlm-pbfv2XVNh4Uww  >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/channel/UCYIye-0ZPNeJH3Av7MzZiTw >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/channel/UCZ-wfY8YgU_sGxMCTHFzQtQ >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/channel/UCZAUWc1RSXghZ_yVoqpMjww >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/channel/UC_Juiy4wsDYLxablAlmyyDw >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/channel/UCbtiMYMK3aHkmG6RttRnzYg >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/channel/UCdDR0pd_0ycGmOQpu3HMi9A  >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/channel/UCdJhEyQEA97X1_yRTr8VDVw  >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/channel/UCe1EBmF7Q6aA7zfFaTXzW_g >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/channel/UCeisWPxnHOYI-GZbeg2dGBw >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/channel/UCfO34F_AmKj731wjg27pjzw >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/channel/UChplJxI8cZTnGtDz6hgdiCQ >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/channel/UCjhfV-tHdoVioBi9XxS6e5g >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/channel/UCk3Bf9yzcDNId5VAfvFksuA >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/channel/UCkjVQbu03kWEo6jFsIyc0pg >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/channel/UClE1d8ijkSealILxE24uDbQ >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/channel/UCmi59PbvyAmFHmWbPlJysIg >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/channel/UCnc88rKMRJ1FzuOWEKrR_Bg >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/channel/UCoYXf0pjDNS4VSNWfwz-vug >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/channel/UCocEreoljpxUUC49RXutTYA >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/channel/UCpJ51QYU5NqYKpYSBzSVMow >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/channel/UCpsAGlQIJVScuCT1pk2e9iQ >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/channel/UCqIOxljlcM5NSIn_xMDcAmw >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/channel/UCrbO3zdo8zy6dZNRVhhvZJA >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/channel/UCt912o-t7fWT2fn9isSHh2w >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/channel/UCvU_GcgRMpiCjPhdRE1uv5A >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/channel/UCwbM2gs_L83cc1Px8vrp7Qg >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/channel/UCwjH2Oi1tEJyTnxWnMmaeaA >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/channel/UCxjMkq1tMAILFSh-SOPN62w >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/channel/UCy0a-4IOqwyQoRMA1VVtJQQ >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/channel/UCyxYrrAi6RUykNzNr6HjQ-g >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/channel/UCzBdopbS7QhWNSpU1eVRJcw >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/0000001230 >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/0411HIBIKI >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/114pass >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/2008rin1 >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/AlondraHaruhi >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/Andrew53670 >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/AtelierNyalice >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/Ciela720 >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/ClaireRieva >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/Eurokigurumi >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/ExeCuteTV >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/Fir100 >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/GURYUUU >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/Hodaraku >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/JoeyAKALD >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/KigHaru >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/KiggyCass >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/KigurumiBasket >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/KigurumiMasks >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/KigurumiNel >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/KigurumiRinRin >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/Knapcon >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/MashiroKigCh >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/Monoyasha >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/Mymynekigurumi >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/RanmaruRei >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/RinaKatase >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/RurudoRan >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/SakuraKigurumi >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/SrueshaSan >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/TN00219533 >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/TSUKIZUMI >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/TheRAGHART >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/TokyoMaskStudio >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/TomoharuKigurumi >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/TryYouMakeItEasy >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/WindLighter >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/Wolf0Donnelie >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/agskigurumi >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/aiko5845 >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/anigaogirls >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/animegaoshop >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/ayamestore >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/carnax489 >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/caugun >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/cazpoke >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/cbd30824 >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/chun03n >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/cicikigi >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/coskighitomi >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/cosmicLandslide >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/dangoazi >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/daysdaizu >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/fantescadesigns >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/garageh2009 >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/ginneko25 >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/hirekatsuichiban1 >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/hirokouji >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/ikehival >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/ikkaisai >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/jovinamask >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/kamsys >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/kanatazeta >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/keep42a >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/kigurumiSabrina >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/kigurumilky >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/kigurumimiyu >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/kigurumishia >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/kimeinishimura >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/kiwikig >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/kiwikig2 >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/kiwikig3 >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/kkkeiv >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/kobapie >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/lingjhuang >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/mechataku >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/megezoufelon >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/miayuisu >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/mobiranights >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/motokokigurumi >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/moukiken >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/nekoyumekuri >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/obankataMaxHeart >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/ozawadango >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/rie1200548213 >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/riunosuke >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/sana2510045 >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/sandaime01 >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/sawaichika >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/sezuna1168 >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/takanet1000 >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/tetetoroort17 >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/thetef2006 >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/totallyfox >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/uera1974 >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/windhp04/Vvideos >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/wtxyama >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/xyzbid >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/zact199x >> doller-IDs.txt
youtube-dl --get-id --ignore-error  http://youtube.com/user/zerosikigami >> doller-IDs.txt
