youtube-dl --ignore-errors --get-id http://www.youtube.com/user/theofficialfacebook >> social-IDs.txt
youtube-dl --ignore-errors --get-id http://www.youtube.com/user/Twitter >> social-IDs.txt
youtube-dl --ignore-errors --get-id http://www.youtube.com/user/TwitterAds >> social-IDs.txt
youtube-dl --ignore-errors --get-id http://www.youtube.com/user/TwitterUniversity >> social-IDs.txt
youtube-dl --ignore-errors --get-id http://www.youtube.com/channel/UCcRd4oOOUPKAvg6vs2P9ReA >> social-IDs.txt
youtube-dl --ignore-errors --get-id http://www.youtube.com/user/OfficialSnapchat >> social-IDs.txt
youtube-dl --ignore-errors --get-id http://www.youtube.com/user/TwitterSmallBiz >> social-IDs.txt
youtube-dl --ignore-errors --get-id http://www.youtube.com/user/FacebookForBusiness >> social-IDs.txt
youtube-dl --ignore-errors --get-id http://www.youtube.com/user/FacebookDevelopers >> social-IDs.txt
youtube-dl --ignore-errors --get-id http://www.youtube.com/user/FacebookJP >> social-IDs.txt
youtube-dl --ignore-errors --get-id http://www.youtube.com/user/pinterestforbusiness >> social-IDs.txt
##Google## >> social-IDs.txt
youtube-dl --ignore-errors --get-id http://www.youtube.com/channel/UCK8sQmJBp8GCxrOtXWBpyEA >> social-IDs.txt
youtube-dl --ignore-errors --get-id http://www.youtube.com/channel/UCtxkCXCD8bWpE8Ea_l4tV2A >> social-IDs.txt
youtube-dl --ignore-errors --get-id http://www.youtube.com/channel/UCL8ZULXASCc1I_oaOT0NaOQ >> social-IDs.txt
##youtube-dl --ignore-errors --get-id http://www.youtube.com/channel/UC9M7-jzdU8CVrQo1JwmIdWA >> social-IDs.txt
##youtube-dl --ignore-errors --get-id http://www.youtube.com/channel/UC_x5XG1OV2P6uZZ5FSM9Ttw >> social-IDs.txt
##youtube-dl --ignore-errors --get-id http://www.youtube.com/channel/UCbmNph6atAoGfqLoCL_duAg >> social-IDs.txt
youtube-dl --ignore-errors --get-id http://www.youtube.com/channel/UCUjlPym2cxucUVPdE8kYOOg >> social-IDs.txt
youtube-dl --ignore-errors --get-id http://www.youtube.com/channel/UCDwLb8FClxNiMa7w6dCO7PQ >> social-IDs.txt
youtube-dl --ignore-errors --get-id http://www.youtube.com/channel/UCrRK02_CbvPEPrDYMQ1l49w >> social-IDs.txt
youtube-dl --ignore-errors --get-id http://www.youtube.com/channel/UCnIQPPwWpO_EFEqLny6TFTw >> social-IDs.txt
youtube-dl --ignore-errors --get-id http://www.youtube.com/channel/UCarDkb_5CKYgASeSMwsh3cg >> social-IDs.txt
youtube-dl --ignore-errors --get-id http://www.youtube.com/channel/UCBmwzQnSoj9b6HzNmFrg_yw >> social-IDs.txt
youtube-dl --ignore-errors --get-id http://www.youtube.com/channel/UCWf2ZlNsCGDS89VBF_awNvA >> social-IDs.txt
youtube-dl --ignore-errors --get-id http://www.youtube.com/channel/UCg44zX42-GjMr5XqyK3RmsQ >> social-IDs.txt
youtube-dl --ignore-errors --get-id http://www.youtube.com/channel/UCvNWzY4IrNeSEDGgRoPTzPA >> social-IDs.txt
youtube-dl --ignore-errors --get-id http://www.youtube.com/channel/UC3x6qC4h-NyuvQBSZYaPKrQ >> social-IDs.txt
youtube-dl --ignore-errors --get-id http://www.youtube.com/channel/UCf4AIjSwE-E2TggCPdm-z-A >> social-IDs.txt
youtube-dl --ignore-errors --get-id http://www.youtube.com/user/GoogATAP >> social-IDs.txt
youtube-dl --ignore-errors --get-id http://www.youtube.com/user/ProjectLoon >> social-IDs.txt
youtube-dl --ignore-errors --get-id http://www.youtube.com/channel/UCCLyNDhxwpqNe3UeEmGHl8g >> social-IDs.txt
youtube-dl --ignore-errors --get-id http://www.youtube.com/user/SearchStories >> social-IDs.txt
##youtube-dl --ignore-errors --get-id http://www.youtube.com/user/GoogleDevelopers >> social-IDs.txt
youtube-dl --ignore-errors --get-id http://www.youtube.com/user/womentechmakers/ >> social-IDs.txt
##youtube-dl --ignore-errors --get-id http://www.youtube.com/user/androiddevelopers >> social-IDs.txt
##youtube-dl --ignore-errors --get-id http://www.youtube.com/user/ChromeDevelopers >> social-IDs.txt
youtube-dl --ignore-errors --get-id http://www.youtube.com/user/googlecloudplatform >> social-IDs.txt
youtube-dl --ignore-errors --get-id http://www.youtube.com/user/StartupLaunch >> social-IDs.txt
youtube-dl --ignore-errors --get-id http://www.youtube.com/channel/UCQqa5UIHtrnpiADC3eHFupw >> social-IDs.txt
youtube-dl --ignore-errors --get-id http://www.youtube.com/channel/UCeo-MamuQVFRcfQmS2N7fhw >> social-IDs.txt
youtube-dl --ignore-errors --get-id http://www.youtube.com/user/GoogleDevBR >> social-IDs.txt
youtube-dl --ignore-errors --get-id http://www.youtube.com/user/DevelopersItaly >> social-IDs.txt
youtube-dl --ignore-errors --get-id http://www.youtube.com/channel/UClKO7be7O9cUGL94PHnAeOA >> social-IDs.txt
youtube-dl --ignore-errors --get-id http://www.youtube.com/user/Googleorg >> social-IDs.txt
