youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UC0Jj_F1MuczVrryGDvYaTcg > speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UC0MtfjKpR1oJ3G84_eaRrCQ >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UC0ZRHSrrlwjRQkRvI03zyvQ >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UC14WVeNARi6YRsQciCEHraw >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UC1EBJfK7ltjYUFyzysKxr1g >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UC1hyBinFskcmKhUTvAaItDA >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UC4irM_9K40EN0d6IStkqZUA >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UC4l7OxUv2acsdLiQlWYBQmw >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UC6vr5gV11oSIstj9mer5AiA >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UC8beGkGK0gLTolEXnNrP5fw >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UC8r1GJE7Y8QPG9D2_7hg9Lg >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UC8ubotgHHKXHfNLm-YbepWQ >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UC8ubotgHHXHfNLm-YbepWQ >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UC9LZTFjOv-VDAkh1-mdv0pA >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UC9ZPMQ3zFQw6REEioeA_PrQ >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UC9cgu0WEZSbJ8e2hCOcsQsg >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UC9nsE5H1cpvi3kwWNiXlbLg >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UC9uV0Y7U4ToIigqFwy-6sAQ >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCANzosaPZ-SsjjNb9pQ3sxg >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCARR4JvL4Z77XJgYB43UQLQ >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCAdA4fXedHjBbr7UnjQURKQ >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCAej6cQu-hYKiIkpG77vF4A >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCAjH5PmcKA3GUHRbhh6Nx3A >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCBARESDB1dvUXUHZwIVHUdw >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCBif6L8-vXoZrX0vu-3hQ5Q >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCBws0QbNTZwRtm74L6fS7hg >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCCgTSs6rFOOVMjzNNUnkStw >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCD0xoMLd4mH2i2rfUYYzdYw >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCDWXCVZ_mfpYYiy-0y5MgWQ >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCFHVZsQ67yF7z7IuB3V5FFw >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCGn-rPKkKlL0Mm3yrpjO4Pg >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCH7Cw4UikkYx08ykuozpZFQ >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCKNd1w-ngPDYvCPGo2Cwqgw >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCMVv6rlATWX41NRXUpE-1PQ >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCONafKLCgdWhufUJXldC4xQ >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCOuR-pJDNOEg3AOcK9Tuiig >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCR4Dbpz_2tgMDqBmWN_uQqQ >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCRQ8cgNWDyuecJcrGc2tytw >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCRQE-JyWUEyi18FVvBG2vJQ >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCRv9PCXUj_q5mlGYFn0HQYA >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCSAftyhcsFemqBgAtP8KsUg >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCSCYnnyVoA-S7aj-gjBZKnw >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCSD-6IZQndvCrk_t-2wi04A >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCSzz9Xa-LDeZTDbxF0M22og >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCTIYxwoe6SAuVhrrm-Wh28g >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCU_rf0QaC3WbZ6F_qsthI6Q >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCVaFyjNhqX9QVfGvPk8ojsQ >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCXD0pNXyQuHtsSAdckwWdiA >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCXIgPz6zFMtm8X_pjMMii7A >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCYJ8oeOpHl5e76Ebeu-fQ1g >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCYxDEf5pGSv2qhsTNXfZ1Ig >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCZ0hWNx3FitfCgXBd_tYHGQ >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UC_LkCz0FiS_1xhFwBZl0CaA >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UC_bPGghdeqhqA4KIBIwRt0w >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCaPWANo31xGCBNc6EUSFcjg >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCaVG0RL6qFY_bFUpgqa83Hw >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCaob6seOmbF4ABN9QPmzXeQ >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCc2t3V85qaTvQz69o9sm43g >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCc8C91EE_psRksX1rAD1gYA >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCcX2jv3QB0KbpaDBlNzm10Q >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCe8IHVBnzqiW0IOdkbWqD2Q >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCegdieCUka-YxQT6f0LhCxQ >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCep2EyviCGmeQDY11xOYYWA >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCfVZfHs9EXH6_bpwbvpRL_g >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCgVgD50ll07dKAzs54Fsfdg >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCgXU79Fg-zyPGMvjEB4pOlA >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCh3LIkJXN3Hs25bj9Ro0LIg >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCiVYS99383wdI9nu6kpd87Q >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCirhcaMp1qCYWeQRXX7C6ZQ >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCj1WyLpmoOg5jLIpy84Hh3Q >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCl6fNuEqKGfoqYx7RD5Oetw >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCm4XydWWbwLcsJG-sPzP6pw >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCmjoe5FPpkHYJaS46v5ZDgg >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCmkAl83Ag33sLsjsEtf8sOg >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCnHQyZvrzLeNtD850cVs2-Q >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCnljldgOkioHy_EYqdHX-eA >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCoXiLJKbcgPh9xpSiU9t-iQ >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCqr9sfYTrQX_kZiylltJtVQ >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCs9I4ZVaZYCRojJdEHoi3cQ >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCsOPHnvYtAqQ0VI3GtG8Eew >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCuN8l8AQRpVVClPHA9CiBxg >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCueiR39jWSHIhLiMGuqmhsA >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCuhaKQkA7aTGj4WxmGYhOZQ >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCw08Cdaa1IDMUWlQBtpNddQ >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCwdYWkqTy0PT54XcemcT3Tg >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCwughh1Vv95lupEvAUjcmVA >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCxGATWGIQo1W1aqgZcex2rw >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCxUt8DwE-gPBgssKn4nwu5g >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCxUt8DwE-gPBgssKn4nwu5g/live >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCyKX8HE0RF4KXpUHenUCAXA >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCy__-DCYxWW7JUU8GqqLn1Q >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCz6xINnvF-Fd_zNZQnxuiYA >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCzPb_N000HdEcz7_ubhvDfw >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/channel/UCzni_F_Z4IUJr77GVw3Z-ZQ >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/user/AzureBladeXIII >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/user/DevilSuzumiya >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/user/Emberwish33 >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/user/LittleTraveller6 >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/user/LordJaneMere >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/user/Mad1Artist >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/user/Marienkafer04 >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/user/McTeamYaoi >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/user/Muffyfluffles >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/user/Nardack43 >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/user/NeruhxRenarde >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/user/Onisasu >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/user/RokkiChan44 >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/user/SONY10000jp >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/user/Soupdraws/videos >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/user/StudioCelestium >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/user/TheAssholesWind >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/user/TheJabbym >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/user/TwistedMyztic >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/user/bokumand  >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/user/dinhoxi >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/user/foxyraspberry >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/user/kentkent172 >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/user/l0chnessa >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/user/lekccl >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/user/licoriceskittles >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/user/luigifreak77 >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/user/platybara >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/user/rizkitsuneki >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/user/ru3na >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/user/shilinTV >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/user/shounore >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/user/tonyjya >> speedpaint-IDs.txt
youtube-dl --ignore-errors --get-id  http://youtube.com/user/xXNearFutureCityX >> speedpaint-IDs.txt
