youtube-dl --get-id http://youtube.com/channel/KSGLIFESTYLE >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UC-AJcHTjclNm7wM3RHYt3QQ  >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UC-j0wSx5QfgXuKXyaroo8cg >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UC0oTSlrC4BrNoOim9omIyUw >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UC1YMFT03cUjU-0xc19M9HBA  >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UC2RMkRM4NHtpSyiwp-XBUVA >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UC3BeAeZ_9o6GKrIRqevYa-g >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UC4qOfqQgdMYWXzg3bjdgNBw >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UC5E7WUHR_inrnRsVU-wbl-w >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UC7nKGof8Xt4Ngc18MK3fvtw >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UC8L1BplQGxZ_FhGc6nzAZ8g >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UC9ZUysCbjFzZ3kvBUR5aisA >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UC9kEIgOOnC_9QTBNw3Wk_JQ  >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCAUj2sRYS1WhpN7dZhzdRSw >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCBeWpva8T0nw4nKOZ29mZGQ >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCBeWpva8T0nw4nKOZ29mZGQ  >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCCPa20aq9HtCWD5vLrjuHeQ >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCDPy_gHuaV_X4GzIU6gCjMw >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCDiEADruDzNceKlLqBtYYcQ >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCGMBnU-22whLthV56DxyJlQ  >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCIe33lwff9WGTvKM3r5PTsw >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCJoevwt_BlGrHZfq5NSPMKA >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCKdWSG-BvO_0CFj6rHeCWYQ >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCL5KPDWXiTsPHyDx3OLL9XQ >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCLE6HyxNnxMyZNi8jtp8JNw >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCNKwA1crOjVMtQo17fq6z_A >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCNjefVj3PRSr2KeRe4dDUkg >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCNsamQit8Jfb1kWhzpGG9xw >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCOHhh4SaO1rJWQXmHGFOecg >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCOekDEFfn39_HtvzudrCZaQ >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCOhd4mgDwECrx2GgwTQSjGQ >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCPBVbUZttRRSASYEc-VLPIQ >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCPS3YjGwXkw3HYGLeTVt_qA  >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCP_0AB7FhsgLSQ3ROS6SJ7A >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCQXkaLw-NfUeKX8AgyYBpQQ >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCQaQhBHmnHqx5nuviCe20Jw >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCRNg0KsljY1Ghzg-1madP4A  >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCRtrCzKb_EeFrgEAEqxGRcw  >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCRzMA0FHUCtKshBp4OJ2bEA >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCTpw-675Yyhx2D9FkAwtuuQ >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCUfFLEmfVEvaeoVsVx12iIA >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCUffBglNRiN2HC1eKHtyF-g >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCUtuo8oCnGGivLyHwEUKdVg >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCVd383sOuMywAJfmCKWwMcw >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCWylkv7CeVEQARif3L9DrwQ >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCXQUGZwQO1HM38q-80ZQQXg >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCYeecqHdiyVu96Zq0UeyL0g  >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCZoN9-QffhxtGv0rL3kQYlA >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UC_46zS8eyXlASt9w5vzZyCA  >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UC_ZE_NKdtiRoV6EAM_3rF0w >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UC__gCsK94-u2RBsjEe2hDAQ >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UC_rHTsIG5Yuig2vb-7gI0iQ >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCa1QqXIe4AghQKzDteBGH9w >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCc29blL_kVDBD06JCi_eRKA >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCc7u0oBuITsrhMPY86mRR_A >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCcSLHWYxKECf8nBqWxMRjzg >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCdJxwrY4dxYYvTPtvU5aZvQ >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCd_PycHQU1t8Q2fnuL8v61Q >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCdia4KZiGRJMkC5he7gyNgA >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCet6BoBVmNilqX_s1NPmz4g >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCgSWDqPI9-4YfY_s4v9btXA >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCgkhcIVvTdRrlVVSi8jOwmQ >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCgtVjGLoN4iwSUMU8xlM9QA >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UChS5nWewDXj0T9h1i6D41Dw >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UChXrAdn94u8XoBX8U52459A >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UChqLRTTW-RIodimWMy17LdQ >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCj8c-sQaYG1cdP9c3UyEhgQ >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCjAuXcRzBl5yJuNuW3r_0UA >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCk4km8302bZ_4dFJ7-bF0XQ >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCkohIAHNDahKKq9tbeTgHng >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCkyGxjKaVb_puKKX_fG68vA >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UClLuadePivz3VMQ_RTY93CQ >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UClfGl4UiN_-Ogdn6hmnEtaQ >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCm7LzT1p5jnQ9_bxyHx8Wcg >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCmV3i02gAyJPOE0-tTTJWwA >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCmqLq-UXZYr2tZ5XadZR7UA >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCmraKGt9OcowKJPqnCvWGvA >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCnkMy5elQYOpa_HVi-41DIw >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCoRij7p3xrPzIT0oi4aSk2g >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCpXZ4mSerU7ZKQJHsLatRXw >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCpap5HFCgO4J_SWWr3WHrqw >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCqd6bvEuQIxZzEdGNww38nQ >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCrER-8CXXlKC7CzbaD28myg >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCrsPvWIEZ4x6Qv9dL6ErXNQ >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCrsPvWIEZ4x6Qv9dL6ErXNQ  >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCsPcDxsn8MmQjT8x6rmkHfg  >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCsWT6FEMf8Qedx6XJv5mwHQ >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCsb6Zb_7BuLHIOuAE7Ir_Kw >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCuIJqlyXu5LCWYyOqYt_A-g >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCuen2o_1aZJGuyC88CANeAg >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCumYYW_AAKuez60bRjWQ3hA >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCvpvM3pA3vyuLieTHGKIwAw  >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCvsLK-VBnXRVRE90eVgm9yA >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCxziU5byQ4aES0cYhpZQWKA  >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCy5xZDP1DF-Mu9eOsLjBTcA >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCy9duPykT_sGyORI4Mwj4Jg >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCybgvwtZ8PmHyzCe0zjNVgg  >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCz2KZRZnkce_0V3Yj3gUVfQ >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCzJ62Dol0wwT5qGMJUgStrw >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/channel/UCzqSiy4Ck1M_xCfQxmSO6kQ >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/user/AllieinWeedyland >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/user/BeautyReflectionn >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/user/Bonghits4Dumbledore1 >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/user/DormGrow >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/user/Erikannabis420 >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/user/Evetteuncovered >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/user/Grow420Guide >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/user/GrowAce >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/user/HaleyIsSoarx  >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/user/HalieeeDude  >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/user/LizKushhh  >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/user/QueenHigherLiving >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/user/SheSmokesJoints  >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/user/SilencedHippie  >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/user/StrainCentral >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/user/TheHighRiseCo >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/user/TheHorrificRIOT >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/user/TrueLifeofATeen >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/user/UrMidnightFlashback  >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/user/WhatACommentary >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/user/coralfish19 >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/user/haleyfourtwenty  >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/user/jessicaharcharjh  >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/user/koarocks1  >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/user/linz23ification  >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/user/mcrlover1234567 >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/user/myviviandme >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/user/peanutbuttercup51198 >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/user/purerandomosity  >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/user/rma116  >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/user/sexiibunii69  >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/user/sk8tergurl020908 >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/user/stonercouple1  >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/user/thedabspot  >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/user/tigerlilly06 >> stoner-IDs.txt
youtube-dl --get-id http://youtube.com/user/x0chi3www >> stoner-IDs.txt
