tubeup --use-download-archive http://youtube.com/channel/UC6PXKhzWTKGuLU7qQJsnoag/videos
tubeup --use-download-archive http://youtube.com/channel/UCIYE5tSuk49aAXnrZObMVVw/videos
tubeup --use-download-archive http://youtube.com/channel/UCR-SCdcKWeZOnCddApH1zdg/videos
tubeup --use-download-archive http://youtube.com/channel/UCdZec7vEex5N0FGYfDP3eyQ/videos
tubeup --use-download-archive http://youtube.com/user/90sShowGillz/videos
tubeup --use-download-archive http://youtube.com/user/90sShowJames/videos
tubeup --use-download-archive http://youtube.com/user/90sShowLoca/videos
tubeup --use-download-archive http://youtube.com/user/90sShowSarah/videos
tubeup --use-download-archive http://youtube.com/user/90sShowShortz/videos
tubeup --use-download-archive http://youtube.com/user/HalloSoupy/videos
tubeup --use-download-archive http://youtube.com/user/JAFSvideos/videos
tubeup --use-download-archive http://youtube.com/user/LOLBUNNEHS/videos
tubeup --use-download-archive http://youtube.com/user/NikkiNarcoticxxx/videos
tubeup --use-download-archive http://youtube.com/user/THAT90sCHANNEL/videos
tubeup --use-download-archive http://youtube.com/user/WTFisANupload/videos
tubeup --use-download-archive http://youtube.com/user/galaxxygal/videos
tubeup --use-download-archive http://youtube.com/user/itsjuneskiibroskii/videos
tubeup --use-download-archive http://youtube.com/user/kikichanXD/videos
tubeup --use-download-archive http://youtube.com/user/xjunesVlogx/videos
