ruby ~/git/deviantart-gallery-downloader/fetch.rb -n http://ajdudebro.deviantart.com/gallery/
ruby ~/git/deviantart-gallery-downloader/fetch.rb -n http://alexandrab24.deviantart.com/gallery/
ruby ~/git/deviantart-gallery-downloader/fetch.rb -n http://apgaga1pegasister.deviantart.com/gallery
ruby ~/git/deviantart-gallery-downloader/fetch.rb -n http://arrrgyle.deviantart.com/gallery/
ruby ~/git/deviantart-gallery-downloader/fetch.rb -n http://cyncaelyx.deviantart.com/gallery/
ruby ~/git/deviantart-gallery-downloader/fetch.rb -n http://digital-snapshots.deviantart.com/gallery/
ruby ~/git/deviantart-gallery-downloader/fetch.rb -n http://dreamininsomniac.deviantart.com/gallery/
ruby ~/git/deviantart-gallery-downloader/fetch.rb -n http://dsozzy.deviantart.com/gallery/
ruby ~/git/deviantart-gallery-downloader/fetch.rb -n http://echan01.deviantart.com/gallery
ruby ~/git/deviantart-gallery-downloader/fetch.rb -n http://hakusfm.deviantart.com/
ruby ~/git/deviantart-gallery-downloader/fetch.rb -n http://hussard-yr.deviantart.com/gallery/
ruby ~/git/deviantart-gallery-downloader/fetch.rb -n http://jabbym.deviantart.com/gallery/
ruby ~/git/deviantart-gallery-downloader/fetch.rb -n http://jessicaelwood.deviantart.com/gallery/
ruby ~/git/deviantart-gallery-downloader/fetch.rb -n http://jynos.deviantart.com/gallery/
ruby ~/git/deviantart-gallery-downloader/fetch.rb -n http://kaitexel.deviantart.com/gallery
ruby ~/git/deviantart-gallery-downloader/fetch.rb -n http://kuvshinov-ilya.deviantart.com/gallery/
ruby ~/git/deviantart-gallery-downloader/fetch.rb -n http://kyleray1.deviantart.com/gallery/
ruby ~/git/deviantart-gallery-downloader/fetch.rb -n http://lollermaz.deviantart.comgallery/
ruby ~/git/deviantart-gallery-downloader/fetch.rb -n http://louiskey13.deviantart.com/gallery/
ruby ~/git/deviantart-gallery-downloader/fetch.rb -n http://lunachi139.deviantart.com/gallery
ruby ~/git/deviantart-gallery-downloader/fetch.rb -n http://marlomarquise.deviantart.com/gallery/
ruby ~/git/deviantart-gallery-downloader/fetch.rb -n http://mrshlapa.deviantart.com/gallery/
ruby ~/git/deviantart-gallery-downloader/fetch.rb -n http://natethebrony.deviantart.com/gallery/
ruby ~/git/deviantart-gallery-downloader/fetch.rb -n http://nathylove5.deviantart.com/gallery/
ruby ~/git/deviantart-gallery-downloader/fetch.rb -n http://nekoloveletter.deviantart.com/gallery/
ruby ~/git/deviantart-gallery-downloader/fetch.rb -n http://otfs.deviantart.com/gallery/
ruby ~/git/deviantart-gallery-downloader/fetch.rb -n http://pablocomics.deviantart.com/gallery
ruby ~/git/deviantart-gallery-downloader/fetch.rb -n http://rizzyda.deviantart.com/gallery/
ruby ~/git/deviantart-gallery-downloader/fetch.rb -n http://s-c.deviantart.com/gallery/
ruby ~/git/deviantart-gallery-downloader/fetch.rb -n http://salmoneatjo0.deviantart.com/gallery/
ruby ~/git/deviantart-gallery-downloader/fetch.rb -n http://shalaraan.deviantart.com/gallery/
ruby ~/git/deviantart-gallery-downloader/fetch.rb -n http://shiniez.deviantart.com/gallery
ruby ~/git/deviantart-gallery-downloader/fetch.rb -n http://snowthewinterkitsune.deviantart.com/gallery/
ruby ~/git/deviantart-gallery-downloader/fetch.rb -n http://sourcefilmmaker.deviantart.com/gallery/
ruby ~/git/deviantart-gallery-downloader/fetch.rb -n http://splashbrush.deviantart.com/gallery/
ruby ~/git/deviantart-gallery-downloader/fetch.rb -n http://tainted-kayla.deviantart.com/gallery/
ruby ~/git/deviantart-gallery-downloader/fetch.rb -n http://thedeathhourxp.deviantart.com/gallery/
ruby ~/git/deviantart-gallery-downloader/fetch.rb -n http://thesourkraut.deviantart.com/
ruby ~/git/deviantart-gallery-downloader/fetch.rb -n http://trahtenberg.deviantart.com/gallery/
ruby ~/git/deviantart-gallery-downloader/fetch.rb -n http://urbanator.deviantart.com/gallery/
ruby ~/git/deviantart-gallery-downloader/fetch.rb -n http://vest.deviantart.com/gallery
ruby ~/git/deviantart-gallery-downloader/fetch.rb -n http://xenolsvectors.deviantart.com/gallery/
ruby ~/git/deviantart-gallery-downloader/fetch.rb -n http://yanhost.deviantart.com/gallery/
