./iagitup.py -u https://github.com/reswitched/CageTheUnicorn
./iagitup.py -u https://github.com/DavidSM64/Quad64
./iagitup.py -u https://github.com/soimort/you-get
./iagitup.py -u https://github.com/makegirlsmoe/makegirls.moe_web
./iagitup.py -u https://github.com/Aixile/chainer-gan-experiments 
./iagitup.py -u https://github.com/corna/me_cleaner
./iagitup.py -u https://github.com/asciimoo/drawille
./iagitup.py -u https://github.com/davebaol/d2x-cios
./iagitup.py -u https://github.com/SeattleMeshnet/meshbox
./iagitup.py -u https://github.com/mogorman/closed_sesame
./iagitup.py -u https://github.com/TheOfficialFloW/VitaShell
./iagitup.py -u https://github.com/Rinnegatamante/rinCheat
./iagitup.py -u https://github.com/Enegnei/JacobAppelbaumLeavesTor
./iagitup.py -u https://github.com/rdanbrook/nestopia
./iagitup.py -u https://github.com/christopherpow/nes-test-roms
./iagitup.py -u https://github.com/henkaku/henkaku
./iagitup.py -u https://github.com/Fire30/PS4-3.55-Code-Execution-PoC
./iagitup.py -u https://github.com/torvalds/linux
./iagitup.py -u https://github.com/dscrts/gay.pl
./iagitup.py -u https://github.com/furrtek/portapack-havoc
./iagitup.py -u https://github.com/AdamLaurie/RFIDIOt 
./iagitup.py -u https://github.com/qntm/base65536
./iagitup.py -u https://github.com/foosel/OctoPrint
./iagitup.py -u https://github.com/cryptocat/crypt
./iagitup.py -u https://github.com/rg3/youtube-dl
./iagitup.py -u https://github.com/wifiphisher/wifiphisher
./iagitup.py -u https://github.com/Xyl2k/TSA-Travel-Sentry-master-keys 
./iagitup.py -u https://github.com/voat/voat
./iagitup.py -u https://github.com/majestrate/nntpchan
./iagitup.py -u https://github.com/maduce/fosscad-repo
./iagitup.py -u https://github.com/nsa-observer/documents
./iagitup.py -u https://github.com/offensive-security/cryptsetup-nuke-keys
./iagitup.py -u https://github.com/Bitmessage/PyBitmessage
./iagitup.py -u https://github.com/jakubroztocil/httpie
./iagitup.py -u https://github.com/cjb/GitTorrent
./iagitup.py -u https://github.com/int0x80/anti-forensics
./iagitup.py -u https://github.com/DanMcInerney/wifijammer
./iagitup.py -u https://github.com/humhub/humhub
