./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/1kmspaint 1kmspaint
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/aardvarkianparadise aardvarkianparadise
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/afrometalmizu afrometalmizu
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/amgitzytrid amgitzytrid
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/aregeecs aregeecs
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/barbellsfm barbellsfm
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/bayernsfm bayernsfm
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/beastlyj0e beastlyj0e
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/beowulf1117 beowulf1117
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/bloodsfm bloodsfm
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/bombowykurczak bombowykurczak
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/bomyman91 bomyman91
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/bravo44 bravo44
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/chris-amateur-artist chris-amateur-artist
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/colonelyobo colonelyobo
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/coot27 coot27
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/creepychimera creepychimera
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/dactyllion dactyllion
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/darktronicksfm darktronicksfm
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/darsovin darsovin
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/dawadd123 dawadd123
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/delosfm delosfm
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/dentol-sfm dentol-sfm
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/desiresfm desiresfm
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/devilbluedragon devilbluedragon
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/devilscry devilscry
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/dotacouch dotacouch
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/dpmaker dpmaker
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/elbatmansfm elbatmansfm
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/ellowas ellowas
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/empathetic-one empathetic-one
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/erobyracs erobyracs
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/froggy-sfm froggy-sfm
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/fugtrup fugtrup
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/funkyriderssfm funkyriderssfm
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/gob-bluth-sfm gob-bluth-sfm
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/gwampsfm gwampsfm
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/hakusfm hakusfm
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/harpertheman harpertheman
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/hentaiforevawork hentaiforevawork
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/highlordarnold highlordarnold
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/honorboundnoobsfm honorboundnoobsfm
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/howdoidoansfm howdoidoansfm
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/hypnorekt hypnorekt
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/indigosfmworks indigosfmworks
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/juliojakers juliojakers
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/jumbogumbo jumbogumbo
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/kalypsofx kalypsofx
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/kamadevasfm kamadevasfm
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/kamadevasfm2 kamadevasfm2
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/khornflake khornflake
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/kingcrave kingcrave
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/kp0988 kp0988
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/kushishekku kushishekku
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/leisurelystudio leisurelystudio
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/lil-potion-shop lil-potion-shop
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/logo365 logo365
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/m1llcake m1llcake
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/m805-sfm m805-sfm
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/marmsfm marmsfm
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/mattdarey91sfm mattdarey91sfm
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/metssfm metssfm
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/mklr-sfm mklr-sfm
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/mrdeviant92 mrdeviant92
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/mrsmugbastard mrsmugbastard
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/nihmz nihmz
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/ninssfm ninssfm
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/nodusfm nodusfm
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/noodlebox-3d noodlebox-3d
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/notlesdiassfm notlesdiassfm
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/nukedsfm nukedsfm
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/nyktamer nyktamer
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/oceanmyhope oceanmyhope
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/olowrider olowrider
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/opiumudkr opiumudkr
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/oshiristudios oshiristudios
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/ourtastytexturesstuff ourtastytexturesstuff
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/pallidsfm pallidsfm
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/penging-arts penging-arts
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/pewposterous pewposterous
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/pino-stuff pino-stuff
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/planet-mojo planet-mojo
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/pockyang pockyang
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/pokedudesfm pokedudesfm
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/premlandio premlandio
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/proverty proverty
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/quick-esfm quick-esfm
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/redmenacekun redmenacekun
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/redmoa redmoa
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/redsamsstuff redsamsstuff
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/rexxart rexxart
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/rrerr-me-again rrerr-me-again
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/runiclodges runiclodges
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/schmoobiesfm schmoobiesfm
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/scoutssfm scoutssfm
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/scrungusbungus scrungusbungus
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/sfmfuntime sfmfuntime
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/sfmnsfw sfmnsfw
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/sfmsnip sfmsnip
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/shittyhorsey shittyhorsey
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/shymorgaine shymorgaine
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/sirdougrattmann sirdougrattmann
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/skykliker-sfm skykliker-sfm
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/snowant snowant
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/snuddy snuddy
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/soulburnin soulburnin
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/spaceghostsfm spaceghostsfm
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/squarepeg3d squarepeg3d
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/srdarko001 srdarko001
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/stealth211 stealth211
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/studiofow studiofow
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/supermarmalademum supermarmalademum
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/tahliansfm tahliansfm
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/tdhxp tdhxp
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/the-grey-yordle the-grey-yordle
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/the-jeixxi the-jeixxi
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/thechosenzero thechosenzero
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/thecunnysseur thecunnysseur
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/thedollwarehouse thedollwarehouse
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/timpossible-purgatory timpossible-purgatory
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/trajan99 trajan99
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/traumalpsfm traumalpsfm
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/turhakex turhakex
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/twitchyanimation twitchyanimation
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/unidentifiedsfm unidentifiedsfm
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/urbanatorsfm urbanatorsfm
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/vgerotica vgerotica
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/vogolsart vogolsart
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/wanksysfm wanksysfm
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/warbuttframe warbuttframe
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/warlordrexx warlordrexx
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/wattchewant wattchewant
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/wubsfm wubsfm
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/xentho xentho
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/xiceowl xiceowl
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/ximemaart ximemaart
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/yagskie yagskie
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/yeero yeero
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/yourbigjohnson yourbigjohnson
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/zalivstok zalivstok
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/zalsfm zalsfm
