./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/amgitzytrid amgitzytrid
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/bayernsfm bayernsfm
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/coot27 coot27
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/devilbluedragon devilbluedragon
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/devilscry devilscry
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/gwampsfm gwampsfm
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/hakusfm hakusfm
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/indigosfmworks indigosfmworks
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/kushishekku kushishekku
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/mklr-sfm mklr-sfm
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/mrsmugbastard mrsmugbastard
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/nodusfm nodusfm
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/notlesdiassfm notlesdiassfm
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/pallidsfm pallidsfm
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/planet-mojo planet-mojo
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/scoutssfm scoutssfm
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/scrungusbungus scrungusbungus
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/snuddy snuddy
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/studiofow studiofow
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/tahliansfm tahliansfm
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/the-grey-yordle the-grey-yordle
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/twitchyanimation twitchyanimation
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/zalivstok zalivstok
