
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/afrometalmizu afrometalmizu
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/amgitzytrid amgitzytrid
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/bayernsfm bayernsfm
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/bombowykurczak bombowykurczak
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/bravo44 bravo44
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/chris-amateur-artist chris-amateur-artist
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/colonelyobo colonelyobo
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/coot27 coot27
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/creepychimera creepychimera
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/dawadd123 dawadd123
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/devilbluedragon devilbluedragon
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/devilscry devilscry
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/ellowas ellowas
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/gwampsfm gwampsfm
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/hakusfm hakusfm
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/highlordarnold highlordarnold
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/indigosfmworks indigosfmworks
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/jumbogumbo jumbogumbo
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/kalypsofx kalypsofx
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/khornflake khornflake
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/kushishekku kushishekku
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/leisurelystudio leisurelystudio
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/lil-potion-shop lil-potion-shop
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/mattdarey91sfm mattdarey91sfm
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/metssfm metssfm
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/mklr-sfm mklr-sfm
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/mrsmugbastard mrsmugbastard
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/nihmz nihmz
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/nodusfm nodusfm
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/notlesdiassfm notlesdiassfm
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/oceanmyhope oceanmyhope
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/oshiristudios oshiristudios
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/pallidsfm pallidsfm
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/penging-arts penging-arts
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/pewposterous pewposterous
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/planet-mojo planet-mojo
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/pokedudesfm pokedudesfm
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/premlandio premlandio
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/runiclodges runiclodges
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/scoutssfm scoutssfm
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/scrungusbungus scrungusbungus
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/skykliker-sfm skykliker-sfm
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/snowant snowant
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/snuddy snuddy
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/soulburnin soulburnin
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/squarepeg3d squarepeg3d
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/studiofow studiofow
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/supermarmalademum supermarmalademum
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/tahliansfm tahliansfm
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/the-grey-yordle the-grey-yordle
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/the-jeixxi the-jeixxi
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/thecunnysseur thecunnysseur
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/twitchyanimation twitchyanimation
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/urbanatorsfm urbanatorsfm
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/vgerotica vgerotica
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/vogolsart vogolsart
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/warlordrexx warlordrexx
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/xiceowl xiceowl
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/ximemaart ximemaart
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/yeero yeero
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/yourbigjohnson yourbigjohnson
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/zalivstok zalivstok
./tumblr_backup.py --save-video -i -I o -O /media/vxbinaca/Storage/tumblr-blogs/zalsfm zalsfm
~                                                                                                        xxi. 
