youtube-dl --ignore-config --get-id http://youtube.com/channel/UC0SInoBjrT0rjYYatww7EiA/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UC0n0NnchNjAT6K8OpEi5LdQ/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UC11i8bbVwU9X__YRImykflw/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UC3Kgs-FyO-mmrXjzipxyvww/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UC6Y0OnPOJhn1ZpdWOLanE5Q/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UC7Xvb6vnx4ADvyXFisUhFyw/videos  >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UC9xHsDvaDKCLWo4SerOtYdA/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCAnax9HdSQy1GQsGyXttKDQ/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCE-RCPNfQZU1_fioN7G6B6w/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCF88rJsqCxmuc521py9MI8w/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCFhhjsNJiLrRS1TcFnwOYGg/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCFq0ipiIzhlHrp0lur4496g/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCFzv5JEx2WBIYf8JhVMqqaw/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCHg23qhb1SQl5b6kmZpELrQ/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCIlWky-zNDoNU4eHTvfu1BQ/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCIr4wYu1mzuowfwfE3RZkiw/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCIzAn--9GtaMcek_RmkW3YQ/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCK_3N4ldsPufN-0PtoHXH1A/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCLGtqbILKgn53RjpgctUgWw/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCLJTepxffpGcFtL-UHxrWIw/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCMqxeEfcrCh38nV3UsL1AcQ/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCQmfoAzx0PfoomW6hgCoqQA/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCQsw5mAeC956hSnrVyPA-Rg >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCR0Wq_aYgTEg8Z3rP9kj8Hw/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCTMq7pbt1QnmVrqwk9dVE2A/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCTW2DcB38U_1rplujOY-SAg/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCUOb4lgSDckZoBzgcvylaLQ/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCUvdK__z3mLqmRCOLIPSVbw/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCVx991b_NjWJU94TGwuc2uw/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCXtgoWAlm-pbfv2XVNh4Uww/videos  >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCYIye-0ZPNeJH3Av7MzZiTw/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCZ-wfY8YgU_sGxMCTHFzQtQ/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCZAUWc1RSXghZ_yVoqpMjww/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UC_Juiy4wsDYLxablAlmyyDw/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCbtiMYMK3aHkmG6RttRnzYg/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCdDR0pd_0ycGmOQpu3HMi9A/videos  >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCdJhEyQEA97X1_yRTr8VDVw/videos  >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCe1EBmF7Q6aA7zfFaTXzW_g/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCeisWPxnHOYI-GZbeg2dGBw/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCfO34F_AmKj731wjg27pjzw/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UChplJxI8cZTnGtDz6hgdiCQ/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCjhfV-tHdoVioBi9XxS6e5g/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCk3Bf9yzcDNId5VAfvFksuA/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCkjVQbu03kWEo6jFsIyc0pg/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UClE1d8ijkSealILxE24uDbQ/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCmi59PbvyAmFHmWbPlJysIg/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCnc88rKMRJ1FzuOWEKrR_Bg/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCoYXf0pjDNS4VSNWfwz-vug/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCocEreoljpxUUC49RXutTYA/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCpJ51QYU5NqYKpYSBzSVMow/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCpsAGlQIJVScuCT1pk2e9iQ/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCqIOxljlcM5NSIn_xMDcAmw/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCrbO3zdo8zy6dZNRVhhvZJA/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCt912o-t7fWT2fn9isSHh2w/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCvU_GcgRMpiCjPhdRE1uv5A/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCwbM2gs_L83cc1Px8vrp7Qg/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCwjH2Oi1tEJyTnxWnMmaeaA/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCxjMkq1tMAILFSh-SOPN62w/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCy0a-4IOqwyQoRMA1VVtJQQ/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCyxYrrAi6RUykNzNr6HjQ-g/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCzBdopbS7QhWNSpU1eVRJcw/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/0000001230/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/0411HIBIKI/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/114pass/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/1975zet/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/2008rin1/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/AlondraHaruhi/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/Andrew53670/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/AtelierNyalice/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/Ciela720/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/ClaireRieva/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/Eurokigurumi/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/ExeCuteTV/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/Fir100/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/GURYUUU/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/Hodaraku/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/JoeyAKALD/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/KigHaru/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/KiggyCass/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/KigurumiBasket/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/KigurumiMasks/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/KigurumiNel/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/KigurumiRinRin/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/Knapcon/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/MashiroKigCh/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/Monoyasha/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/Mymynekigurumi/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/RanmaruRei/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/RinaKatase/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/RurudoRan/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/SakuraKigurumi/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/SrueshaSan/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/TN00219533/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/TSUKIZUMI/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/TheRAGHART/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/TokyoMaskStudio/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/TomoharuKigurumi/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/TryYouMakeItEasy/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/WindLighter/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/Wolf0Donnelie/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/agskigurumi/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/aiko5845/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/anigaogirls/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/animegaoshop/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/ayamestore/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/carnax489/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/caugun/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/cazpoke/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/cbd30824/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/chun03n/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/cicikigi/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/coskighitomi/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/cosmicLandslide/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/dangoazi/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/daysdaizu/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/fantescadesigns/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/garageh2009/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/ginneko25/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/hirekatsuichiban1/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/hirokouji/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/ikehival/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/ikkaisai/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/jovinamask/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/kamsys/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/kanatazeta/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/keep42a/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/kigurumiSabrina/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/kigurumilky/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/kigurumimiyu/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/kigurumishia/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/kimeinishimura/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/kiwikig/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/kiwikig2/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/kiwikig3/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/kkkeiv/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/kobapie/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/lingjhuang/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/mechataku/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/megezoufelon/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/miayuisu/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/mobiranights/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/motokokigurumi/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/moukiken/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/nekoyumekuri/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/obankataMaxHeart/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/ozawadango/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/rie1200548213/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/riunosuke/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/sana2510045/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/sandaime01/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/sawaichika/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/sezuna1168/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/takanet1000/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/tetetoroort17/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/thetef2006/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/totallyfox/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/uera1974/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/windhp04/Vvideos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/wtxyama/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/xyzbid/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/zact199x/videos >> KIG-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/zerosikigami/videos >> KIG-IDS.txt
