youtube-dl --ignore-config --get-id https://www.youtube.com/user/theofficialfacebook >> SOCIALMEDIA-IDS.txt
youtube-dl --ignore-config --get-id https://www.youtube.com/user/Twitter >> SOCIALMEDIA-IDS.txt
youtube-dl --ignore-config --get-id https://www.youtube.com/user/TwitterAds >> SOCIALMEDIA-IDS.txt
youtube-dl --ignore-config --get-id https://www.youtube.com/user/TwitterUniversity >> SOCIALMEDIA-IDS.txt
youtube-dl --ignore-config --get-id https://www.youtube.com/channel/UCcRd4oOOUPKAvg6vs2P9ReA >> SOCIALMEDIA-IDS.txt
youtube-dl --ignore-config --get-id https://www.youtube.com/user/OfficialSnapchat >> SOCIALMEDIA-IDS.txt
youtube-dl --ignore-config --get-id https://www.youtube.com/user/TwitterSmallBiz >> SOCIALMEDIA-IDS.txt
youtube-dl --ignore-config --get-id https://www.youtube.com/user/FacebookForBusiness >> SOCIALMEDIA-IDS.txt
youtube-dl --ignore-config --get-id https://www.youtube.com/user/FacebookDevelopers >> SOCIALMEDIA-IDS.txt
youtube-dl --ignore-config --get-id https://www.youtube.com/user/FacebookJP >> SOCIALMEDIA-IDS.txt
youtube-dl --ignore-config --get-id https://www.youtube.com/user/pinterestforbusiness >> SOCIALMEDIA-IDS.txt
##Google## >> SOCIALMEDIA-IDS.txt
youtube-dl --ignore-config --get-id https://www.youtube.com/channel/UCK8sQmJBp8GCxrOtXWBpyEA >> SOCIALMEDIA-IDS.txt
youtube-dl --ignore-config --get-id https://www.youtube.com/channel/UCtxkCXCD8bWpE8Ea_l4tV2A >> SOCIALMEDIA-IDS.txt
youtube-dl --ignore-config --get-id https://www.youtube.com/channel/UCL8ZULXASCc1I_oaOT0NaOQ >> SOCIALMEDIA-IDS.txt
##youtube-dl --ignore-config --get-id https://www.youtube.com/channel/UC9M7-jzdU8CVrQo1JwmIdWA >> SOCIALMEDIA-IDS.txt
##youtube-dl --ignore-config --get-id https://www.youtube.com/channel/UC_x5XG1OV2P6uZZ5FSM9Ttw >> SOCIALMEDIA-IDS.txt
##youtube-dl --ignore-config --get-id https://www.youtube.com/channel/UCbmNph6atAoGfqLoCL_duAg >> SOCIALMEDIA-IDS.txt
youtube-dl --ignore-config --get-id https://www.youtube.com/channel/UCUjlPym2cxucUVPdE8kYOOg >> SOCIALMEDIA-IDS.txt
youtube-dl --ignore-config --get-id https://www.youtube.com/channel/UCDwLb8FClxNiMa7w6dCO7PQ >> SOCIALMEDIA-IDS.txt
youtube-dl --ignore-config --get-id https://www.youtube.com/channel/UCrRK02_CbvPEPrDYMQ1l49w >> SOCIALMEDIA-IDS.txt
youtube-dl --ignore-config --get-id https://www.youtube.com/channel/UCnIQPPwWpO_EFEqLny6TFTw >> SOCIALMEDIA-IDS.txt
youtube-dl --ignore-config --get-id https://www.youtube.com/channel/UCarDkb_5CKYgASeSMwsh3cg >> SOCIALMEDIA-IDS.txt
youtube-dl --ignore-config --get-id https://www.youtube.com/channel/UCBmwzQnSoj9b6HzNmFrg_yw >> SOCIALMEDIA-IDS.txt
youtube-dl --ignore-config --get-id https://www.youtube.com/channel/UCWf2ZlNsCGDS89VBF_awNvA >> SOCIALMEDIA-IDS.txt
youtube-dl --ignore-config --get-id https://www.youtube.com/channel/UCg44zX42-GjMr5XqyK3RmsQ >> SOCIALMEDIA-IDS.txt
youtube-dl --ignore-config --get-id https://www.youtube.com/channel/UCvNWzY4IrNeSEDGgRoPTzPA >> SOCIALMEDIA-IDS.txt
youtube-dl --ignore-config --get-id https://www.youtube.com/channel/UC3x6qC4h-NyuvQBSZYaPKrQ >> SOCIALMEDIA-IDS.txt
youtube-dl --ignore-config --get-id https://www.youtube.com/channel/UCf4AIjSwE-E2TggCPdm-z-A >> SOCIALMEDIA-IDS.txt
youtube-dl --ignore-config --get-id https://www.youtube.com/user/GoogATAP >> SOCIALMEDIA-IDS.txt
youtube-dl --ignore-config --get-id https://www.youtube.com/user/ProjectLoon >> SOCIALMEDIA-IDS.txt
youtube-dl --ignore-config --get-id https://www.youtube.com/channel/UCCLyNDhxwpqNe3UeEmGHl8g >> SOCIALMEDIA-IDS.txt
youtube-dl --ignore-config --get-id https://www.youtube.com/user/SearchStories >> SOCIALMEDIA-IDS.txt
##youtube-dl --ignore-config --get-id https://www.youtube.com/user/GoogleDevelopers >> SOCIALMEDIA-IDS.txt
youtube-dl --ignore-config --get-id https://www.youtube.com/user/womentechmakers/ >> SOCIALMEDIA-IDS.txt
##youtube-dl --ignore-config --get-id https://www.youtube.com/user/androiddevelopers >> SOCIALMEDIA-IDS.txt
##youtube-dl --ignore-config --get-id https://www.youtube.com/user/ChromeDevelopers >> SOCIALMEDIA-IDS.txt
youtube-dl --ignore-config --get-id https://www.youtube.com/user/googlecloudplatform >> SOCIALMEDIA-IDS.txt
youtube-dl --ignore-config --get-id https://www.youtube.com/user/StartupLaunch >> SOCIALMEDIA-IDS.txt
youtube-dl --ignore-config --get-id https://www.youtube.com/channel/UCQqa5UIHtrnpiADC3eHFupw >> SOCIALMEDIA-IDS.txt
youtube-dl --ignore-config --get-id https://www.youtube.com/channel/UCeo-MamuQVFRcfQmS2N7fhw >> SOCIALMEDIA-IDS.txt
youtube-dl --ignore-config --get-id https://www.youtube.com/user/GoogleDevBR >> SOCIALMEDIA-IDS.txt
youtube-dl --ignore-config --get-id https://www.youtube.com/user/DevelopersItaly >> SOCIALMEDIA-IDS.txt
youtube-dl --ignore-config --get-id https://www.youtube.com/channel/UClKO7be7O9cUGL94PHnAeOA >> SOCIALMEDIA-IDS.txt
youtube-dl --ignore-config --get-id https://www.youtube.com/user/Googleorg >> SOCIALMEDIA-IDS.txt
