##youtube-dl --ignore-config --get-id http://youtube.com/user/alanscampos ## Needs curation before ripping >> SPEEDPAINTING-IDS.txt
##youtube-dl --ignore-config --get-id http://youtube.com/user/drawingwiffwaffle ## Needs curation before ripping >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UC0Jj_F1MuczVrryGDvYaTcg >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UC0MtfjKpR1oJ3G84_eaRrCQ >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UC0ZRHSrrlwjRQkRvI03zyvQ >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UC14WVeNARi6YRsQciCEHraw >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UC1EBJfK7ltjYUFyzysKxr1g >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UC1hyBinFskcmKhUTvAaItDA >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UC4irM_9K40EN0d6IStkqZUA >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UC4l7OxUv2acsdLiQlWYBQmw >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UC6vr5gV11oSIstj9mer5AiA >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UC8r1GJE7Y8QPG9D2_7hg9Lg >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UC8ubotgHHKXHfNLm-YbepWQ >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UC8ubotgHHXHfNLm-YbepWQ >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UC9LZTFjOv-VDAkh1-mdv0pA >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UC9ZPMQ3zFQw6REEioeA_PrQ >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UC9cgu0WEZSbJ8e2hCOcsQsg >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UC9nsE5H1cpvi3kwWNiXlbLg >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UC9uV0Y7U4ToIigqFwy-6sAQ >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCANzosaPZ-SsjjNb9pQ3sxg >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCARR4JvL4Z77XJgYB43UQLQ >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCAdA4fXedHjBbr7UnjQURKQ >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCAej6cQu-hYKiIkpG77vF4A >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCAjH5PmcKA3GUHRbhh6Nx3A >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCBARESDB1dvUXUHZwIVHUdw >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCBif6L8-vXoZrX0vu-3hQ5Q >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCBws0QbNTZwRtm74L6fS7hg >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCCgTSs6rFOOVMjzNNUnkStw >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCD0xoMLd4mH2i2rfUYYzdYw >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCDWXCVZ_mfpYYiy-0y5MgWQ >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCFHVZsQ67yF7z7IuB3V5FFw >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCGn-rPKkKlL0Mm3yrpjO4Pg >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCH7Cw4UikkYx08ykuozpZFQ >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCKNd1w-ngPDYvCPGo2Cwqgw >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCMVv6rlATWX41NRXUpE-1PQ >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCONafKLCgdWhufUJXldC4xQ >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCOuR-pJDNOEg3AOcK9Tuiig >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCR4Dbpz_2tgMDqBmWN_uQqQ >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCRQ8cgNWDyuecJcrGc2tytw >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCRQE-JyWUEyi18FVvBG2vJQ >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCRv9PCXUj_q5mlGYFn0HQYA >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCSAftyhcsFemqBgAtP8KsUg >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCSCYnnyVoA-S7aj-gjBZKnw >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCSD-6IZQndvCrk_t-2wi04A >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCSzz9Xa-LDeZTDbxF0M22og >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCTIYxwoe6SAuVhrrm-Wh28g >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCU_rf0QaC3WbZ6F_qsthI6Q >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCVaFyjNhqX9QVfGvPk8ojsQ >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCXD0pNXyQuHtsSAdckwWdiA >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCXIgPz6zFMtm8X_pjMMii7A >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCYJ8oeOpHl5e76Ebeu-fQ1g >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCYxDEf5pGSv2qhsTNXfZ1Ig >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCZ0hWNx3FitfCgXBd_tYHGQ >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UC_LkCz0FiS_1xhFwBZl0CaA >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UC_bPGghdeqhqA4KIBIwRt0w >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCaPWANo31xGCBNc6EUSFcjg >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCaVG0RL6qFY_bFUpgqa83Hw >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCaob6seOmbF4ABN9QPmzXeQ >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCc2t3V85qaTvQz69o9sm43g >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCc8C91EE_psRksX1rAD1gYA >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCcX2jv3QB0KbpaDBlNzm10Q >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCe8IHVBnzqiW0IOdkbWqD2Q >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCegdieCUka-YxQT6f0LhCxQ >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCep2EyviCGmeQDY11xOYYWA >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCfVZfHs9EXH6_bpwbvpRL_g >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCgVgD50ll07dKAzs54Fsfdg >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCgXU79Fg-zyPGMvjEB4pOlA >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCh3LIkJXN3Hs25bj9Ro0LIg >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCiVYS99383wdI9nu6kpd87Q >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCirhcaMp1qCYWeQRXX7C6ZQ >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCj1WyLpmoOg5jLIpy84Hh3Q >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCl6fNuEqKGfoqYx7RD5Oetw >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCm4XydWWbwLcsJG-sPzP6pw >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCmjoe5FPpkHYJaS46v5ZDgg >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCnHQyZvrzLeNtD850cVs2-Q >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCnljldgOkioHy_EYqdHX-eA >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCoXiLJKbcgPh9xpSiU9t-iQ >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCqr9sfYTrQX_kZiylltJtVQ >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCs9I4ZVaZYCRojJdEHoi3cQ >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCsOPHnvYtAqQ0VI3GtG8Eew >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCuN8l8AQRpVVClPHA9CiBxg >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCueiR39jWSHIhLiMGuqmhsA >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCuhaKQkA7aTGj4WxmGYhOZQ >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCw08Cdaa1IDMUWlQBtpNddQ >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCwdYWkqTy0PT54XcemcT3Tg >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCwughh1Vv95lupEvAUjcmVA >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCxGATWGIQo1W1aqgZcex2rw >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCxUt8DwE-gPBgssKn4nwu5g >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCxUt8DwE-gPBgssKn4nwu5g/live >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCyKX8HE0RF4KXpUHenUCAXA >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCy__-DCYxWW7JUU8GqqLn1Q >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCz6xINnvF-Fd_zNZQnxuiYA >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCzPb_N000HdEcz7_ubhvDfw >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCzni_F_Z4IUJr77GVw3Z-ZQ >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/AzureBladeXIII >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/DevilSuzumiya >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/Emberwish33 >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/LittleTraveller6 >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/LordJaneMere >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/Mad1Artist >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/Marienkafer04 >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/McTeamYaoi >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/Muffyfluffles >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/Nardack43 >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/NeruhxRenarde >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/Onisasu >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/RokkiChan44 >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/SONY10000jp >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/Soupdraws/videos >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/StudioCelestium >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/TheAssholesWind >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/TheJabbym >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/TwistedMyztic >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/bokumand  >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/dinhoxi >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/foxyraspberry >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/kentkent172 >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/l0chnessa >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/lekccl >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/licoriceskittles >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/luigifreak77 >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/platybara >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/rizkitsuneki >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/ru3na >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/shilinTV >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/shounore >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/tonyjya >> SPEEDPAINTING-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/xXNearFutureCityX >> SPEEDPAINTING-IDS.txt
