youtube-dl --ignore-config --get-id http://youtube.com/channel/UC-AJcHTjclNm7wM3RHYt3QQ  >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UC-j0wSx5QfgXuKXyaroo8cg >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UC0oTSlrC4BrNoOim9omIyUw >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UC1YMFT03cUjU-0xc19M9HBA  >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UC2RMkRM4NHtpSyiwp-XBUVA >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UC4qOfqQgdMYWXzg3bjdgNBw >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UC5E7WUHR_inrnRsVU-wbl-w >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UC7nKGof8Xt4Ngc18MK3fvtw >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UC8L1BplQGxZ_FhGc6nzAZ8g >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UC9ZUysCbjFzZ3kvBUR5aisA >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UC9kEIgOOnC_9QTBNw3Wk_JQ  >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCAUj2sRYS1WhpN7dZhzdRSw >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCBeWpva8T0nw4nKOZ29mZGQ >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCBeWpva8T0nw4nKOZ29mZGQ  >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCCPa20aq9HtCWD5vLrjuHeQ >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCDPy_gHuaV_X4GzIU6gCjMw >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCDiEADruDzNceKlLqBtYYcQ >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCGMBnU-22whLthV56DxyJlQ  >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCIe33lwff9WGTvKM3r5PTsw >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCKdWSG-BvO_0CFj6rHeCWYQ >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCL5KPDWXiTsPHyDx3OLL9XQ >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCLE6HyxNnxMyZNi8jtp8JNw >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCNKwA1crOjVMtQo17fq6z_A >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCNjefVj3PRSr2KeRe4dDUkg >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCNsamQit8Jfb1kWhzpGG9xw >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCOekDEFfn39_HtvzudrCZaQ >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCPBVbUZttRRSASYEc-VLPIQ >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCPS3YjGwXkw3HYGLeTVt_qA  >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCP_0AB7FhsgLSQ3ROS6SJ7A >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCQaQhBHmnHqx5nuviCe20Jw >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCRtrCzKb_EeFrgEAEqxGRcw  >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCTpw-675Yyhx2D9FkAwtuuQ >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCUffBglNRiN2HC1eKHtyF-g >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCUtuo8oCnGGivLyHwEUKdVg >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCVd383sOuMywAJfmCKWwMcw >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCWylkv7CeVEQARif3L9DrwQ >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCXQUGZwQO1HM38q-80ZQQXg >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UC_46zS8eyXlASt9w5vzZyCA  >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UC_ZE_NKdtiRoV6EAM_3rF0w >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UC__gCsK94-u2RBsjEe2hDAQ >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UC_rHTsIG5Yuig2vb-7gI0iQ >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCa1QqXIe4AghQKzDteBGH9w >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCc29blL_kVDBD06JCi_eRKA >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCc7u0oBuITsrhMPY86mRR_A >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCcSLHWYxKECf8nBqWxMRjzg >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCdJxwrY4dxYYvTPtvU5aZvQ >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCd_PycHQU1t8Q2fnuL8v61Q >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCgSWDqPI9-4YfY_s4v9btXA >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCgkhcIVvTdRrlVVSi8jOwmQ >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCgtVjGLoN4iwSUMU8xlM9QA >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UChS5nWewDXj0T9h1i6D41Dw >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCj8c-sQaYG1cdP9c3UyEhgQ >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCjAuXcRzBl5yJuNuW3r_0UA >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCk4km8302bZ_4dFJ7-bF0XQ >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCkohIAHNDahKKq9tbeTgHng >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCkyGxjKaVb_puKKX_fG68vA >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UClLuadePivz3VMQ_RTY93CQ >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UClfGl4UiN_-Ogdn6hmnEtaQ >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCm7LzT1p5jnQ9_bxyHx8Wcg >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCmV3i02gAyJPOE0-tTTJWwA >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCmqLq-UXZYr2tZ5XadZR7UA >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCmraKGt9OcowKJPqnCvWGvA >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCnkMy5elQYOpa_HVi-41DIw >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCoRij7p3xrPzIT0oi4aSk2g >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCpXZ4mSerU7ZKQJHsLatRXw >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCpap5HFCgO4J_SWWr3WHrqw >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCrsPvWIEZ4x6Qv9dL6ErXNQ >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCrsPvWIEZ4x6Qv9dL6ErXNQ  >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCsPcDxsn8MmQjT8x6rmkHfg  >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCsWT6FEMf8Qedx6XJv5mwHQ >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCsb6Zb_7BuLHIOuAE7Ir_Kw >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCuIJqlyXu5LCWYyOqYt_A-g >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCuen2o_1aZJGuyC88CANeAg >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCumYYW_AAKuez60bRjWQ3hA >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCvpvM3pA3vyuLieTHGKIwAw  >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCvsLK-VBnXRVRE90eVgm9yA >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCxziU5byQ4aES0cYhpZQWKA  >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCy5xZDP1DF-Mu9eOsLjBTcA >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCy9duPykT_sGyORI4Mwj4Jg >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCybgvwtZ8PmHyzCe0zjNVgg  >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/channel/UCzJ62Dol0wwT5qGMJUgStrw >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/AllieinWeedyland >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/Bonghits4Dumbledore1 >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/DormGrow >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/Erikannabis420 >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/Evetteuncovered >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/Grow420Guide >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/GrowAce >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/HaleyIsSoarx  >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/HalieeeDude  >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/LizKushhh  >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/QueenHigherLiving >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/SheSmokesJoints  >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/SilencedHippie  >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/TheHighRiseCo >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/TheHorrificRIOT >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/TrueLifeofATeen >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/UrMidnightFlashback  >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/WhatACommentary >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/coralfish19 >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/haleyfourtwenty  >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/jessicaharcharjh  >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/koarocks1  >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/linz23ification  >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/mcrlover1234567 >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/myviviandme >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/peanutbuttercup51198 >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/peanutbuttercup51198  >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/purerandomosity  >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/rma116  >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/sexiibunii69  >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/sk8tergurl020908 >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/stonercouple1  >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/thedabspot  >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://youtube.com/user/tigerlilly06  >> WEEDTUBERS-IDS.txt
youtube-dl --ignore-config --get-id http://www.youtube.com/channel/UCrER-8CXXlKC7CzbaD28myg >> WEEDTUBERS-IDS.txt
