youtube-dl --ignore-config --get-id --ignore-error http://vimeo.com/fetishfactory > vimeo-IDs.sh
youtube-dl --ignore-config --get-id --ignore-error http://vimeo.com/toplesstopics >> vimeo-IDs.sh
youtube-dl --ignore-config --get-id --ignore-error http://vimeo.com/sukaoff >> vimeo-IDs.sh
youtube-dl --ignore-config --get-id --ignore-error http://vimeo.com/exey >> vimeo-IDs.sh
youtube-dl --ignore-config --get-id --ignore-error http://vimeo.com/user26842840 >> vimeo-IDs.sh
#youtube-dl --ignore-config --get-id --ignore-error http://vimeo.com/junnnktank >> vimeo-IDs.sh
youtube-dl --ignore-config --get-id --ignore-error http://vimeo.com/user1944739 >> vimeo-IDs.sh
youtube-dl --ignore-config --get-id --ignore-error http://vimeo.com/user24127837 >> vimeo-IDs.sh
youtube-dl --ignore-config --get-id --ignore-error http://vimeo.com/kuvshinovilya >> vimeo-IDs.sh
