youtube-dl --ignore-config --get-id http://pscp.tv/2high4lifeTv/ >>  2high4lifeTv.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/3tokes/ >> 3tokes.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/6Chel6sea6/ >> 6Chel6sea6.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/AlondraBravoo/ >> AlondraBravoo.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/ArtsAndKush/ >> ArtsAndKush.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/Blazingit365/ >> Blazingit365.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/CannaYaas/ >> CannaYaas.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/CoralReefer420/ >> CoralReefer420.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/CoureyPie/ >> CoureyPie.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/Dabbing_Granny/ >> Dabbing_Granny.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/DakotaPaige/ >> DakotaPaige.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/DakotaPaige420/ >> DakotaPaige420.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/DandyasLionz >> DandyasLionz.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/HannahWeedWorld >> HannahWeedWorld.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/HighFromPiper/ >> HighFromPiper.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/IAmStella420/ >> IAmStella420.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/JoJosmiles/ >> JoJosmiles.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/KushNKurls/ >> KushNKurls.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/Lilmissmj >> Lilmissmj.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/LindaDMuzzey/ >> LindaDMuzzey.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/Macdizzle420/ >> Macdizzle420.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/MarMarkila/ >> MarMarkila.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/ModestMaryJane/ >> ModestMaryJane.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/NessiesKitches/ >> NessiesKitches.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/PositiveSmash/ >> PositiveSmash.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/Rachellovesyou/ >> Rachellovesyou.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/RavenclawReefer/ >> RavenclawReefer.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/RawOG420/ >> RawOG420.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/RemedyTHC_tv/ >> RemedyTHC_tv.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/SheSmokesJoints/ >> SheSmokesJoints.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/SilencedHippie/ >> SilencedHippie.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/SkullKid_/ >> SkullKid_.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/SlowerFuture >> SlowerFuture.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/StoneySpike/ >> StoneySpike.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/TheDabSpot/ >> TheDabSpot.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/TwitchyBlaze/ >> TwitchyBlaze.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/TwoStonesGirls/ >> TwoStonesGirls.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/WhynterP >> WhynterP.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/_kassidymae/ >> _kassidymae.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/acidsouul >> acidsouul.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/amandalacyxo/ >> amandalacyxo.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/batgirlbrit/ >> batgirlbrit.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/bby_serena/ >> bby_serena.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/brigittah91/ >> brigittah91.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/dabmom420/ >> dabmom420.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/dabpwincess/ >> dabpwincess.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/dsativa/ >> dsativa.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/dudeletsflyaway/ >> dudeletsflyaway.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/earlymorningbonghits/ >> earlymorningbonghits.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/earth2julia/ >> earth2julia.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/gingerkidlife/ >> gingerkidlife.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/godshideouscreation/ >> godshideouscreation.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/haley420/ >> haley420.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/highfelisha/ >> highfelisha.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/hiiighhprincessss/ >> hiiighhprincessss.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/honeynuggs >> honeynuggs.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/jaylikejordans/ >> jaylikejordans.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/joyyyyag/ >> joyyyyag.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/juliadabs/ >> juliadabs.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/kid4nothing/ >> kid4nothing.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/ladyabigale/ >> ladyabigale.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/longlivetheweeds >> longlivetheweeds.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/marylovesglass/ >> marylovesglass.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/misspeeksa >> misspeeksa.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/moneyygame/ >> moneyygame.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/mskushton420/ >> mskushton420.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/paperseatbelttt/ >> paperseatbelttt.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/rachelhiiiii >> rachelhiiiii.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/richie_v09/ >> richie_v09.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/royalcannabis/ >> royalcannabis.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/sofaseahorses/ >> sofaseahorses.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/sweetsunriseX >> sweetsunriseX.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/theHazelverse/ >> theHazelverse.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/thedanksideofthemoon/ >> thedanksideofthemoon.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/thehashcorner/ >> thehashcorner.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/thelittlefae/ >> thelittlefae.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/themisslw/ >> themisslw.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/therealemeliee/ >> therealemeliee.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/theweedqueen/ >> theweedqueen.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/vnoriegaaa/ >> vnoriegaaa.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/weedbreath/ >> weedbreath.sh 
youtube-dl --ignore-config --get-id http://pscp.tv/weedgoddess/ >> weedgoddess.sh 
