python3.7 -m tubeup --use-download-archive --metadata=collection:healthyaddictvideos http://twitch.tv/healthyaddict/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/Djhyena/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/SashaHippie/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/afoxinspaceshow/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/akidearest/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/amadanigames/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/ashelylovecraft/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/bobdunga/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/charlscarroll/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/chubbykittengaming/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/cursedarachnid/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/demongrimalkin/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/dokiiboii/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/erabb/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/femboyconnie/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/gamecatt/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/grandifloru/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/gunsarefun911/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/haley420/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/hitsuji_senpai/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/hydeart/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/jadevow/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/jellykin/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/khg777/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/kimimoons/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/kimochisensei/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/kittendaddyhub/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/kristiplays/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/kushbushcrits/all/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/kyleeasakura/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/lolwut8D/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/mowtendoo/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/neeko/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/nyannyancosplay/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/positivesmash/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/producerchik/all/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/projektmelody/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/r0x4nn3/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/rayvinrainn/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/ryuudog_/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/sae_jin/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/samtron5000/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/saruei/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/sashagrey/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/sh0rtychan/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/shadbasemurdertv/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/sifyro/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/smonroeshow/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/softmoe/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/spoonee/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/spoonyone/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/sweetcheeksplays/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/sydsnap/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/textfilesdotcom/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/thedanklank/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/thekommandoblog/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/theschon/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/thespherehunter/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/toplesstopics/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/turaru/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/virescence_/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/xxautumnivyxx/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/yakirisu/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/yamatoworks/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/yifanlu/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/yuninja8/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/zeldacw/videos?filter=archives&sort=time
python3.7 -m tubeup --use-download-archive --metadata=collection:twitchstreams http://twitch.tv/videos/zonesama/videos?filter=archives&sort=time
