#tubeup --use-download-archive --metadata=collection:tubeup http://youtube.com/channel/UCKH9HfYY_GEcyltl2mbD5lA/videos ##NJ nerds
#tubeup --use-download-archive --metadata=collection:tubeup http://youtube.com/channel/UC_-9rxe8VZI-tUQJWEig4mA/videos ##NJ nerds
#tubeup --use-download-archive --metadata=collection:tubeup http://youtube.com/channel/UCnbUeHmpeHAX3xED4fRXKeg/videos ## Vaporwave
#tubeup --use-download-archive --metadata=collection:tubeup http://youtube.com/user/ejmillennium/videos ##NJ nerds
#tubeup --use-download-archive --metadata=collection:tubeup http://youtube.com/user/gotenks6/videos ##NJ nerds
#tubeup --use-download-archive --metadata=collection:tubeup http://youtube.com/user/katTcritic/videos ##NJ nerds
tubeup --use-download-archive --metadata=collection:tubeup http://youtube.com/channel/UC1fSp9Qpp8tT982OumLS5Hg/videos
tubeup --use-download-archive --metadata=collection:tubeup http://youtube.com/channel/UC4QFrwuzxJ2eC7Q2iDrlJFg/videos
tubeup --use-download-archive --metadata=collection:tubeup http://youtube.com/channel/UC5hie5xBr7qENWVD_kfsiew/videos
tubeup --use-download-archive --metadata=collection:tubeup http://youtube.com/channel/UC7yPuRdd4ZKhJQueiVnjd2A/videos
tubeup --use-download-archive --metadata=collection:tubeup http://youtube.com/channel/UC8EvY5Cky6LM9tTE07kk2kQ/video ## Vaporwave
tubeup --use-download-archive --metadata=collection:tubeup http://youtube.com/channel/UC8aG3LDTDwNR1UQhSn9uVrw/videos
tubeup --use-download-archive --metadata=collection:tubeup http://youtube.com/channel/UCAo6nC6I9yk2X4xqQThhhew/videos
tubeup --use-download-archive --metadata=collection:tubeup http://youtube.com/channel/UCEAqHbeIpPERhniNjQyR7EQ/videos
tubeup --use-download-archive --metadata=collection:tubeup http://youtube.com/channel/UCECs2QPEUC-3fNsDYJM1BjQ/videos
tubeup --use-download-archive --metadata=collection:tubeup http://youtube.com/channel/UCEUrQzNPvDQoEMNswAr8mCA/videos
tubeup --use-download-archive --metadata=collection:tubeup http://youtube.com/channel/UCF30c7L3SiutEP9m_HhBZAw
tubeup --use-download-archive --metadata=collection:tubeup http://youtube.com/channel/UCGCqGI3f2WSDnfRjrD1Cj_Q/videos
tubeup --use-download-archive --metadata=collection:tubeup http://youtube.com/channel/UCKNQ5RbMm42xVVARTJoEsIg/videos
tubeup --use-download-archive --metadata=collection:tubeup http://youtube.com/channel/UCKcibNqpgyXwInQHS4s_I4Q/videos
tubeup --use-download-archive --metadata=collection:tubeup http://youtube.com/channel/UCKlA7qF9XKwu79ULYmVu28w/videos
tubeup --use-download-archive --metadata=collection:tubeup http://youtube.com/channel/UCNEo4Lb14UTkcqBZ9nKwyTg/videos
tubeup --use-download-archive --metadata=collection:tubeup http://youtube.com/channel/UCS6F1cpcSoJkztme19_KIzw/videos
tubeup --use-download-archive --metadata=collection:tubeup http://youtube.com/channel/UCT5y7BAocgM-PeXpVCvyG4g/videos
tubeup --use-download-archive --metadata=collection:tubeup http://youtube.com/channel/UCTRpJwRhE-uifL7fTRVe48g
tubeup --use-download-archive --metadata=collection:tubeup http://youtube.com/channel/UCTlQFIx8RUus4R3zYAUHHYA/videos
tubeup --use-download-archive --metadata=collection:tubeup http://youtube.com/channel/UCWH4JkQWioU3vTAritHDnAA/videos
tubeup --use-download-archive --metadata=collection:tubeup http://youtube.com/channel/UCWMPmKJ8GmmUvI5ZC0V2VsA/videos
tubeup --use-download-archive --metadata=collection:tubeup http://youtube.com/channel/UCZZFrPKyH-Le2uoPGnn5jyg/videos
tubeup --use-download-archive --metadata=collection:tubeup http://youtube.com/channel/UCaIg15JhvGgPwdurGNqjJUg
tubeup --use-download-archive --metadata=collection:tubeup http://youtube.com/channel/UCdpkbiiCFHVPZrSYEEWyDdw/videos
tubeup --use-download-archive --metadata=collection:tubeup http://youtube.com/channel/UCgHUzh9T2DHvSDZcnILqH8g/videos
tubeup --use-download-archive --metadata=collection:tubeup http://youtube.com/channel/UCjPao-PMHoC1IBurivhfGFQ/videos
tubeup --use-download-archive --metadata=collection:tubeup http://youtube.com/channel/UCkDXV1ELQBVV4BuLR-FyfkA/videos
tubeup --use-download-archive --metadata=collection:tubeup http://youtube.com/channel/UCkfqhn4lyofss8PM1IubDgA/videos
tubeup --use-download-archive --metadata=collection:tubeup http://youtube.com/channel/UCmyiBfu_idd4fdSQuA6yjew/videos
tubeup --use-download-archive --metadata=collection:tubeup http://youtube.com/channel/UCnzq0TEm7vMLUe4wEumA39A
tubeup --use-download-archive --metadata=collection:tubeup http://youtube.com/channel/UCox0RC7bP_wafzpRmlnD9EQ
tubeup --use-download-archive --metadata=collection:tubeup http://youtube.com/channel/UCp4oMaqaY0hIoT9jafj1g8g/videos
tubeup --use-download-archive --metadata=collection:tubeup http://youtube.com/channel/UCp8tB7kfhjvmgY2wUDBlaMA/videos
tubeup --use-download-archive --metadata=collection:tubeup http://youtube.com/channel/UCpMMcYVSnqOIJA11vBnFngQ/videos
tubeup --use-download-archive --metadata=collection:tubeup http://youtube.com/channel/UCuimpDKCmUaW6qnMMp7XE7Q/videos
tubeup --use-download-archive --metadata=collection:tubeup http://youtube.com/user/0dutch/videos
tubeup --use-download-archive --metadata=collection:tubeup http://youtube.com/user/BraveTheWorldChannel/videos
tubeup --use-download-archive --metadata=collection:tubeup http://youtube.com/user/DNALounge/videos
tubeup --use-download-archive --metadata=collection:tubeup http://youtube.com/user/HiMyNameIsRoxi/videos
tubeup --use-download-archive --metadata=collection:tubeup http://youtube.com/user/LeoPirate/videos
tubeup --use-download-archive --metadata=collection:tubeup http://youtube.com/user/Ooolalaa/videos
tubeup --use-download-archive --metadata=collection:tubeup http://youtube.com/user/ProfessorFennec/videos
tubeup --use-download-archive --metadata=collection:tubeup http://youtube.com/user/RareNargacuga/videos
tubeup --use-download-archive --metadata=collection:tubeup http://youtube.com/user/TLCSprout/videos
tubeup --use-download-archive --metadata=collection:tubeup http://youtube.com/user/TheRealParis/videos
tubeup --use-download-archive --metadata=collection:tubeup http://youtube.com/user/debuglive/videos
tubeup --use-download-archive --metadata=collection:tubeup http://youtube.com/user/dsscdse/videos
tubeup --use-download-archive --metadata=collection:tubeup http://youtube.com/user/etanthe4th/videos
tubeup --use-download-archive --metadata=collection:tubeup http://youtube.com/user/flippingpages1014/videos
tubeup --use-download-archive --metadata=collection:tubeup http://youtube.com/user/littleloca/videos
tubeup --use-download-archive --metadata=collection:tubeup http://youtube.com/user/lonelygirl15/videos
tubeup --use-download-archive --metadata=collection:tubeup http://youtube.com/user/shachiNT/videos
tubeup --use-download-archive --metadata=collection:tubeup http://youtube.com/user/stevieryan/videos
tubeup --use-download-archive --metadata=collection:tubeup http://youtube.com/watch?v=xTJC2RkcLEs&list=PLD0NeEbRY7VTkw1GBrnsZAUIrOTOjyzaw
