## tubeup --use-download-archive --metadata=collection:tubeup http://vimeo.com/junnnktank ## DEAD
##tubeup --use-download-archive --metadata=collection:tubeup http://vimeo.com/toplesstopics
##tubeup --use-download-archive --metadata=collection:tubeup http://vimeo.com/user8923725
tubeup --use-download-archive --metadata=collection:tubeup http://vimeo.com/chrismday
tubeup --use-download-archive --metadata=collection:tubeup http://vimeo.com/exey
tubeup --use-download-archive --metadata=collection:tubeup http://vimeo.com/fetishfactory
tubeup --use-download-archive --metadata=collection:tubeup http://vimeo.com/kuvshinovilya
tubeup --use-download-archive --metadata=collection:tubeup http://vimeo.com/mrtello
tubeup --use-download-archive --metadata=collection:tubeup http://vimeo.com/sukaoff
tubeup --use-download-archive --metadata=collection:tubeup http://vimeo.com/user1944739
tubeup --use-download-archive --metadata=collection:tubeup http://vimeo.com/user24127837
tubeup --use-download-archive --metadata=collection:tubeup http://vimeo.com/user26842840
tubeup --use-download-archive --metadata=collection:tubeup http://vimeo.com/vnbateman
tubeup --use-download-archive --metadata=collection:weedtubers http://vimeo.com/TheDabSpot
tubeup --use-download-archive --metadata=collection:weedtubers http://vimeo.com/growpotcheaply
